---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: centos-7.0
  - name: centos-6.6

suites:
  - name: centos-7
    excludes: [ "centos-6.6" ]
    run_list:
      - recipe[audit-cis::centos7-100]
    attributes:

  - name: centos6
    excludes: [ "centos-7.0" ]
    run_list:
    - recipe[audit-cis::centos6-110]
    attributes:
